### PR TITLE
fix(Makefile)-fix-mount-errors-in-windows

### PR DESCRIPTION
**Pull request by SARDONYX-sard**
If you feel this is unnecessary, please close this pull request. :)

- In PowerShell, the `pwd` command does not accept the current path string in the same way as bash.
Therefore, this pull request uses `ifeq` in the Makefile to branch the command.

There are several possible options for the command.

(Option1)
`alias pwd` -> `Get-Location` and considering the profile override maybe we should use `Get-Location` instead of `pwd`

```Makefile
PWD_CMD := powershell -NoProfile -Command "Write-Output $$(Get-Location)"
```

 (Option2)
Instead of PowerShell, we may want to use the following command.

```Makefile
PWD_CMD := cmd /c "echo %CD%"
```

(Another option)
Differences in this kind of shell can be left to docker.
Using `docker-compose.yml`

```yml
version: "3.9"

services:
  app:
    build:
      context: ./ # Dockerfile/URL Path
      dockerfile: Dockerfile
    image: dinghao188/rcore-tutorial:dev # as image name
    tty: true # == `docker -t`
    stdin_open: true # == `docker -i`
    volumes:
      - ./:/mnt/
```

### CODE REVIEW

**Comment by SARDONYX-sard** [comment]
I forgot that there was a `-NoProfile` option for the profile overwrite issue...

see more: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-noprofile

```Makefile
PWD_CMD := poweshell -NoProfile "$$(Get-Location).Path"
```

**Comment by codychau** [comment]
your nvim configuration look great

**Comment by SARDONYX-sard** [comment]
> your nvim configuration look great

Thank you.
At this time I was using something called Lunarvim.

https://github.com/lunarvim/lunarvim

**Comment by chyyuu** [comment]
Thank you! I think if you use wsl2(ubuntu 20.04) in windows to develop rcore-tutorial-v3, you will meet much less problems.

**Pull request closed without merging**
